#!/bin/bash
# Show common Yandex regions

echo "=== Common Region IDs ==="
echo ""
echo "Countries:"
echo "  225 - Россия"
echo "  159 - Казахстан"
echo "  187 - Украина"
echo "  149 - Беларусь"
echo ""
echo "Federal Districts (Russia):"
echo "  3   - Центральный ФО"
echo "  17  - Северо-Западный ФО"
echo "  40  - Приволжский ФО"
echo "  52  - Уральский ФО"
echo "  59  - Сибирский ФО"
echo "  73  - Южный ФО"
echo "  26  - Дальневосточный ФО"
echo ""
echo "Major Cities:"
echo "  213 - Москва"
echo "  2   - Санкт-Петербург"
echo "  54  - Екатеринбург"
echo "  65  - Новосибирск"
echo "  43  - Казань"
echo "  35  - Краснодар"
echo "  47  - Нижний Новгород"
echo "  39  - Ростов-на-Дону"
echo "  51  - Самара"
echo "  172 - Уфа"
echo ""
echo "Moscow Region:"
echo "  1   - Москва и область"
echo "  213 - Москва (город)"
echo "  10716 - Московская область"
echo ""
echo "Use these IDs with --regions parameter in other scripts."
echo "Example: bash scripts/top_requests.sh --phrase \"test\" --regions 213"
