#!/bin/sh
# Show common Yandex Search API region IDs

echo "=== Common Region IDs (Yandex Search API) ==="
echo ""
echo "Countries:"
echo "  225   - Россия"
echo "  159   - Казахстан"
echo "  187   - Украина"
echo "  149   - Беларусь"
echo "  983   - Турция"
echo "  84    - США"
echo ""
echo "Federal Districts (Russia):"
echo "  3     - Центральный ФО"
echo "  17    - Северо-Западный ФО"
echo "  40    - Приволжский ФО"
echo "  52    - Уральский ФО"
echo "  59    - Сибирский ФО"
echo "  73    - Южный ФО"
echo "  26    - Дальневосточный ФО"
echo ""
echo "Major Cities:"
echo "  213   - Москва"
echo "  2     - Санкт-Петербург"
echo "  54    - Екатеринбург"
echo "  65    - Новосибирск"
echo "  43    - Казань"
echo "  35    - Краснодар"
echo "  47    - Нижний Новгород"
echo "  39    - Ростов-на-Дону"
echo "  51    - Самара"
echo "  172   - Уфа"
echo "  56    - Челябинск"
echo "  66    - Омск"
echo "  11    - Пермь"
echo "  14    - Воронеж"
echo ""
echo "Moscow Region:"
echo "  1     - Москва и область"
echo "  213   - Москва (город)"
echo "  10716 - Московская область"
echo ""
echo "Use these IDs with --region-id parameter in search scripts."
echo "Example: bash scripts/web_search_sync.sh --query \"test\" --region-id 213"
